### Регистрация покупателя
POST http://localhost:8000/api/user/register/
Content-Type: application/json

{
    "username": "buyer4",
    "password": "buyer123455", 
    "password2": "buyer123455",
    "email": "buyer@example.com",
    "first_name": "Иван",
    "last_name": "Покупатель",
    "type": "buyer",
    "company": "ООО Покупатель",
    "position": "Менеджер"
}

### Авторизация покупателя
POST http://localhost:8000/api/user/login/
Content-Type: application/json

{
    "username": "denistamoykin",
    "password": "12wqasxz"
}

### Получить список магазинов
GET http://localhost:8000/api/shops/

### Получить список категорий
GET http://localhost:8000/api/categories/

### Получить все товары
GET http://localhost:8000/api/products/

### Получить товары с фильтрацией
GET http://localhost:8000/api/products/?category_id=1

### Получить детали товара
GET http://localhost:8000/api/products/1/

### Получить профиль пользователя
GET http://localhost:8000/api/user/profile/
Authorization: Token {{buyer_token}}

### Добавить контакт
POST http://localhost:8000/api/user/contacts/
Authorization: Token {{buyer_token}}
Content-Type: application/json

{
    "city": "Москва",
    "street": "Ленина",
    "house": "10",
    "apartment": "25",
    "phone": "+79991234567"
}

### Получить список контактов
GET http://localhost:8000/api/user/contacts/
Authorization: Token {{buyer_token}}

### Добавить товар в корзину
POST http://localhost:8000/api/basket/
Authorization: Token {{buyer_token}}
Content-Type: application/json

{
    "product_info": 1,
    "quantity": 2
}

### Посмотреть корзину
GET http://localhost:8000/api/basket/
Authorization: Token {{buyer_token}}

### Оформить заказ из корзины
POST http://localhost:8000/api/orders/
Authorization: Token {{buyer_token}}
Content-Type: application/json

{
    "contact_id": 1
}

### Посмотреть историю заказов
GET http://localhost:8000/api/orders/
Authorization: Token {{buyer_token}}

### Подтвердить заказ с отправкой email
POST http://localhost:8000/api/orders/1/confirm/
Authorization: Token {{buyer_token}}

### Проверить статус задачи
GET http://localhost:8000/api/tasks/ваш_task_id/
Authorization: Token {{buyer_token}}

### Запуск импорта через админку (требует is_staff=True)
POST http://localhost:8000/api/supplier/admin/import/
Authorization: Token ваш_токен_администратора
Content-Type: application/json

{
    "shop_id": 1,
    "import_url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}